### ISSUE TITLE
annotated-wl-pprint

### ISSUE THREAD

**Issue by jystic** [abhinav/language-thrift#3]
Thanks for this fantastic library, I really appreciate how nicely your data types are laid out.

I noticed you're going to quite some trouble to have both text and ANSI pretty printing. I thought you might be interested in [annotated-wl-pprint](https://hackage.haskell.org/package/annotated-wl-pprint) which might allow you to do that and more without all the `CPP`.

David Christiansen presented on how it is used in Idris at [HIW 2015](https://www.youtube.com/watch?v=m7BBCcIDXSg).

**Comment by abhinav** [comment]
Thanks! This looks interesting. I'll consider switching over.

**Comment by abhinav** [comment]
I've dropped `wl-pprint` support. Only `ansi-wl-pprint` is supported now. I'll switch to `annotated-wl-pprint` or `wl-pprint-extras` if a use case for semantic annotations comes up. Closing this meanwhile.
